### ISSUE TITLE
Add basic database.

### ISSUE THREAD

**Issue by saltydk** [Biospheere/promcord#155]
Whenever the docker container is restarted all the message statistics reset, would be nice if the latest "stats" where written to a file that is loaded again when starting up.

**Comment by emyfops** [comment]
> Whenever the docker container is restarted all the message statistics reset, would be nice if the latest "stats" where written to a file that is loaded again when starting up.

This can be configured with prometheus I think
And adding a database to fetch hundred of data will significantly affect the performances

**Comment by saltydk** [comment]
I don't think you're following what I meant. The totals need to be stored otherwise the suggested grafana template resets. This has nothing to do with prometheus not storing it but totals starting over.

**Comment by nimarion** [comment]
Closing this as an extra database for storing message count is out of scope for this project. The counter metric used should be used with the rate function. 
https://www.robustperception.io/how-does-a-prometheus-counter-work/
