### ISSUE TITLE
How I can add my ID

### ISSUE THREAD

**Issue by pijn-tech** [Biospheere/promcord#79]
It works but i want to add my server how I do that?

**Comment by Biospheere** [comment]
You can add the bot to your server using this invite url. Just replace CLIENTID with the id from the [Discord Developer Portal](https://discord.com/developers/applications). After that you should be able to see the id of your discord server in the Grafana Dashboard. 
https://discord.com/oauth2/authorize?client_id=CLIENTID&scope=bot
![image](https://user-images.githubusercontent.com/23435250/87853189-70f13a00-c908-11ea-97d6-ea7761393c8b.png)
